from .user import *
from .auth import *
from .Assigment import *
from .AssigmentTemp import *
from .TeachingStratigies import *
from .TeachingStratigiesTemp import *
from .Rationale import *
from .RationaleTemp import *
from .Content import *
from .ContentTemp import *
from .course import *
from .description import *
from .descriptionTemp import *
from .LearningOutcomes import *
from .LearningOutcomeTemp import *
from .Resoruces import *
from .ResourceTemp import *
from .template import *
