from .user import *
from .Assigment import *
from .AssigmentTemp import *
from .TeachingStratigies import *
from .TeachingStratigiesTemp import *
from .Rationale import *
from .RationaleTemp import *
from .CELTmember import *
from .Content import *
from .ContentTemp import *
from .course import *
from .departMember import *
from .description import *
from .DescriptionTemp import *
from .LearningOutcomes import *
from .LearningOutcomesTemp import *
from .Resources import *
from .ResourcesTemp import *
from .template import *
